---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-admin-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: dev-sa # Name is case sensitive
  namespace: dev
roleRef:
  kind: Role
  name: dev-admin
  apiGroup: rbac.authorization.k8s.io