apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: prod-cluster-rolebinding
subjects:
- kind: ServiceAccount # here in the place of serviceaccount, we can provide the user or group.
  name: prod-sa # Name is case sensitive
  apiGroup: ""
  namespace: prod
roleRef:
  kind: ClusterRole
  name: Cluster-admin
  apiGroup: rbac.authorization.k8s.io