apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" does not required for cluster role, it works on the cluster level security.
  # But when cluster role is linked to a service account via role binding, so the cluster role ppermission only apply to the namespace in which the role-binding is created.
  name: Cluster-admin
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["*"]
  verbs: ["*"]